language: node_js
node_js:
  - "5"
  - "6"
  - "6.9.2"
  - "node"
install:
  - npm install
before_script:
  - sleep 5
  - mongo friends-matcher --eval 'db.addUser("matchbox", "lighter");'
script:
  - npm test
after_script:
  - "npm run test-cov"
notifications:
  email: false
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
services:
  - mongodb
